blog_on_rails/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  
  get 'sessions/new'

  get 'posts/index'
  get '/posts', {to: 'posts#index', as: :index_posts}
  
  get 'posts/new', {to: "posts#new", as: :new_post}
  
  post 'posts/new', {to: 'posts#create', as: :posts}
  get '/posts/:id', {to: 'posts#show', as: :post}

  get 'post/:id/edit', {to: 'posts#edit', as: :edit_post}
  

  patch '/posts/:id', {to: 'posts#update'}

  delete '/posts/:id', {to: 'posts#destroy'}

  resources :posts do
    resources :comments, only:
      [:create, :destroy]
    end
    
    get '/user/:id/password', to: 'users#password', as: :edit_password
    
    patch '/user/:id/password', to: "users#update_password", as: :update_password
    
    resources :users, shallow: true, only: [:new, :create, :edit, :update] 
    
    
    

    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end
end

blog_on_rails/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    if user.is_admin?
      can :manage, :all
    end

    alias_action :create, :read, :update, :destroy, to: :crud


    can :crud, Post do |post|
      post.user == user
    end

    can :crud, Comment do |comment|
      comment.user == user
    end

  end
end

blog_on_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog_on_rails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates :body, presence: true
end

blog_on_rails/app/models/post.rb
class Post < ApplicationRecord

    has_many :comments, dependent: :destroy
    belongs_to :user

    validates :title, presence: true, uniqueness: { case_sensitive: false }   
    validates:body, presence: {message: "Please add a message"}, length: {minimum: 50}
end


# The title column must be present and unique.
# The body column must be present and contain at least 50 characters.

blog_on_rails/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts, dependent: :nullify
    has_many :comment, dependent: :nullify

    attr_accessor :current_password

    def full_name
        "#{first_name} #{last_name}"
    end 


end

blog_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    # private

    def current_user
        if session[:user_id].present?
            @current_user ||= User.find_by(id: session[:user_id])
           
        end
    end

    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end

    helper_method :user_signed_in?

    def authenticate_user!
        unless user_signed_in?
            flash[:alert] = "please sign in"
        end
    end
end

blog_on_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find params[:post_id]
        @comment = Comment.new comment_params
        @comment.user = current_user
        @comment.post = @post
        if @comment.save
            redirect_to post_path(@post),          
            notice: "Post Added"

        else
            @comments = @post.comments.order(created_at: :desc) 
      render 'posts/show'
        end
    end

    def destroy
        @post = Post.find params[:post_id]
        @comment = Comment.find params[:id]
        if can? :crud, @comment
            @comment.destroy
            redirect_to post_path(@post), notice:"comment deleted"
        else
            redirect_to post_path(@post)
        end

    end

    private

    def comment_params
        params.require(:comment).permit(:body)
    end

  
end
 

blog_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :edit, :update, :destroy]

  before_action :find_post, only: [:show, :edit, :update, :destroy]

  before_action :authorize!, only: [:edit, :destroy, :update, :new]

  def index
    @posts= Post.all.order(created_at: :desc)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc) 
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      flash[:notice] = "post created"
      redirect_to post_path(@post)
    else
      render :new
    end
    
  end

  def edit

  end

  def update
    if @post.update post_params
      redirect_to post_path(@post)
    else
        render :edit
    end
  end

  def destroy
      # flash[:notice] = "post deleted"
    @post.destroy 
    redirect_to index_posts_path
  end

  private

    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end

      def authorize!
        redirect_to root_path, alert: "Not autherized" unless can?(:crud, @post)
      end
end

blog_on_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "logged in"
    else
      flash[:alert] = "wrong email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "logged out"
  end

end

blog_on_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :password, :update, :update_password]
  before_action :authenticate_user!, only: [:edit, :update, :update_password]
  before_action :user_params, only: [:update, :update_password]
  


  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render :new 
    end
  end

  def edit

  end
  
  def update
    
    if @user.update user_params

        @current_user = @user
        redirect_to root_path

    else

      render :edit

    end
  end

  

  def password
   
  end
  
  def update_password
   # alert user if current password is not right
   # update if password is right

    if @user&.authenticate params[:user][:current_password]
  
        if @user.update user_params
         redirect_to root_path
      
        end

    else

        flash[:danger] = "password not updated"
        redirect_to edit_password_path 
        
        # edit_password_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
  
  def find_user
    @user = User.find(params[:id])
  end


end

blog_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_on_rails/app/helpers/comments_helper.rb
module CommentsHelper
end

blog_on_rails/app/helpers/posts_helper.rb
module PostsHelper
end

blog_on_rails/app/helpers/sessions_helper.rb
module SessionsHelper
end

blog_on_rails/app/helpers/users_helper.rb
module UsersHelper
end

blog_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
<body>
  <header>
    <div class="nav-icon">
      <%= image_tag "td3diconleft.png", class:"icon"%>
      <%=  link_to "Blog On Rails", index_posts_path, class:"icon-text" %>
      <%= image_tag "td3diconright.png", class:"icon icon_hidden"%>
    </div>
      <%= link_to "Home", index_posts_path, class:"nav-item"  %>
      <%= link_to "New Post", new_post_path,class:"nav-item"  %>

    <%  if user_signed_in? %>
      <%= link_to "#{current_user.first_name}", edit_user_path(current_user), class:"nav-item" %>
      <%= link_to "Log out", sessions_path, method: :delete, data: {confirm: "Sure you want to Log out?"}, class: "nav-item"%>


    <% else %>
      <%= link_to "Login", new_session_path,class:"nav-item"  %>
      <%= link_to "New User", new_user_path,class:"nav-item"  %>
    <% end %>

  </header>

    <% flash.each do |type, message| %>
              <div class="flash flash-  <%= type %>" >
              <%= message %>
            <% end %>

    <%= yield %>





      <div class="footing">

        Created by T. Smith 
      </div>
</body>
</html>

blog_on_rails/app/views/posts/_form_comment.html.erb
   <%= form_with(model: [@post, @comment], local:true) do |f| %>
            <% if @comment.errors.any?  %>
                <ul>
                    <% @comment.errors.full_messages.each do |msg|  %>
                        <li><%= msg %></li>
                    <% end  %>
                </ul>
            <% end %>
            <div class="form-comment">
            <div>
            <%= f.text_area :body, rows: 4, placeholder: "Enter comment here", class:"comment-text-area" %>
           </div>
           <div>
            <%= f.submit "Submit Comment", class:"form-btn" %>
           </div>
</div>
        <% end %>

blog_on_rails/app/views/posts/_form_edit.html.erb
<div class="form-width">
<%  if @post.errors.any? %>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end  %>
    </ul>
<% end %>

    <%= form_for @post do |f| %>
        <div class="form">
            <div class="form-item">
                <%= f.label :title, class:"form-label" %>
                <%= f.text_field :title, rows: 1,class:"form-field" %>
            </div>
            <div class="form-item" >
                <%= f.label :body, class:"form-label" %>
                <%= f.text_area :body, rows: 5, class:"form-field" %>
            </div>
            <div>
                <%= f.submit "Save Edits", class:'form-btn' %>
            </div>
        </div>
    <% end %>
</div>

blog_on_rails/app/views/posts/edit.html.erb
<div class="form-div">

<%= render "form_edit" %>


</div>

blog_on_rails/app/views/posts/index.html.erb
<article>

<% @posts.each do |post| %>

<div class="card">
<div class="card-header">
<%= link_to post.title, post_path(post), class:"card-header-text" %>
</div>
<div class="card-body">
<%= link_to post.body, post_path(post), class:"card-body-text" %>
</div>
</div>
<% end  %>



</article>

blog_on_rails/app/views/posts/new.html.erb
<article>

<%= render "form_edit" %>   

</article>

blog_on_rails/app/views/posts/show.html.erb
<article>
<div class="container">
    <div class="card-blog">
       
            <h2 class="card-header"> <%= @post.title %> </h2>
            <p class="card-body card-body-text"><%= @post.body %> </p>
             <p class=" user"> 
             <%=  @post.user&.full_name %>
             </p>
            <p class="card-created">Post created <%=  time_ago_in_words(@post.created_at) %> ago </p>
        
        <div>
<% if can? :crud, @post %>
            <%= link_to "Edit", edit_post_path(@post), class:"form-btn" %>
            <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Delete post"}, class:"form-btn" %>
<% end %>
        </div>
        </div>
        </div>
    </div>
    <div class="card-comment">
        <h3 >Comments</h3>
        <div>
            <%= render "/posts/form_comment" %>
        </div>



        <div>
            <% @comments.each do |comment| %>
            <div class="top-border comment-log">
            <%= comment.body %>

            <div class="comment-log-footing">
            <div>
            <%= comment.user&.full_name %>
            </div>
            <div>

            <%=  time_ago_in_words(comment.created_at)  %> 
            </div>
            <% if can? :crud, comment%>
            <div>

                <%= link_to "Delete comment", post_comment_path(@post, comment), method: :delete, data: {confirm: "Are you sure?"}, class:"comment-btn" %>
            </div>
            <% end %>
            </div>
            </div>
            <% end %>
        </div>
 
</article>

blog_on_rails/app/views/users/_form_user.html.erb
<div>
<% if @user.errors.any?  %>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>

            <li>
                <%= msg %>
            </li>
        <% end%>
    </ul>

<% end %>

<%= form_with(model: @user, local: true) do |f|%>

    <div class="form">

        <div class="form-item">
            <%= f.label :first_name, class:"form-label" %>
            <%= f.text_field :first_name,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.label :last_name, class:"form-label" %>
            <%= f.text_field :last_name,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.label :email, class:"form-label" %>
            <%= f.email_field :email,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.label :password, class:"form-label" %>
            <%= f.password_field :password,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.label :password_confirmation, class:"form-label" %>
            <%= f.password_field :password_confirmation,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.submit "Create User", class:'form-btn' %>
        </div>
    </div>

<% end %>
</div>

blog_on_rails/app/views/users/edit.html.erb
<% if @current_user.errors.any? %>

    <ul>
        <% @current_user.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>

<% end %>

<%= form_with(model: @current_user, url: user_path, local: true) do |f|%>

    <div class="form">

        <div class="form-item">
            <%= f.label :first_name, class:"form-label" %>
            <%= f.text_field :first_name,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.label :last_name, class:"form-label" %>
            <%= f.text_field :last_name,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.label :email, class:"form-label" %>
            <%= f.email_field :email,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.submit "Save Edits", method: :put, class:'form-btn'%>

            <%= link_to "Change password", edit_password_path, class:'form-btn' %>
        </div>
</div>

<% end %>

blog_on_rails/app/views/users/new.html.erb
<%= render "form_user" %>

blog_on_rails/app/views/users/password.html.erb
<%  if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end  %>
    </ul>
<% end %>

 <div class="form">

    <%= form_with(model: @user, url: edit_password_path, local: true) do |f| %>

        <div class="form-item">
            <%= f.label :current_password, class:"form-label form-label-long" %>
            <%= f.password_field :current_password,class:"form-field" %>
        </div>

        <div class="form-item">
            <%= f.label :new_password, class:"form-label form-label-long" %>
            <%= f.password_field :password,class:"form-field " %>
        </div>

        <div class="form-item">
            <%= f.label :password_confirmation, class:"form-label form-label-long" %>
            <%= f.password_field :password_confirmation,class:"form-field" %>
        </div>

        <div class="form-item">
            <%=f.submit "Update Password", method: :patch, class:'form-btn' %>
        </div>
    </div>
<% end %>